🧪 Blog App - Controllers Specs
DevKaranJ/Blog pull request #5
Opened 2024-01-16 12:24 UTC by DevKaranJ

**In this project, your task is to set up tests for the controllers recently added to your Blog app.**

- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Ensure that for each action you check:

- [ ] If the response status was correct.
- [ ] If a correct template was rendered.
- [ ] If the response body includes correct placeholder text.

2024-01-16 12:39 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @DevKaranJ👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with controller specs. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 12:39 UTC, thecodechaser commented on spec/requests/posts_spec.rb
>      end
- [ ] Please make sure to check the below for each actions(index and show) for user and post controllers. Currently, you're checking only status. You should place the tests only in files re to posts and users, don't create other files for tests example `controllers_spec.rb`

![image](https://github.com/DevKaranJ/Blog/assets/83803414/c1c5b1d0-61e5-411c-94bf-22070ab5bae7)

2024-01-16 13:45 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @DevKaranJ👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- Good job with controller specs.
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-16 13:45 UTC, thecodechaser commented on spec/requests/posts_spec.rb
>    end
- [ ] Good job adding the missing tests for the post-index action as requested by me previously but you missed adding the tests for the post-show action. Please make sure to add all the above tests for post-show action as well and all tests should pass without any errors.

2024-01-16 13:45 UTC, thecodechaser commented on spec/requests/posts_spec.rb
>    describe 'GET /index' do
- [ ] https://github.com/DevKaranJ/Blog/blob/1b443ff641535651becf7513e2f1c578ee7e5741/spec/requests/users_spec.rb#L3-L16
 
  - Please make sure to add other missing tests for the user index and user show actions as requested by me previously and all tests should pass without any errors.
 
![image](https://github.com/DevKaranJ/Blog/assets/83803414/b01739d6-7e6d-45f6-944f-6d57cadd8e56)

2024-01-16 13:45 UTC, thecodechaser commented on spec/requests/posts_spec.rb
> +      expect(response.body).to include('List of Posts') # If the correct content was rendered.
- [ ] All the tests are failing, Please make sure to fix it and all tests should pass without any errors.

![image](https://github.com/DevKaranJ/Blog/assets/83803414/69783f2b-e796-44b0-90db-c50231b7755d)

2024-01-17 11:55 UTC, skyv26 approved these changes
## Hi @DevKaranJ, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJhMzBhODJmYjQwOGJiYTYxNTllMzM4MzcxZDY2NDcyMTgwODUxMyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/IL4iTvQH0MjS/giphy.gif)

## Highlights
- Implemented the features as suggested by previous code reviewer ✅ 
- All tests are passing ✅
![image](https://github.com/DevKaranJ/Blog/assets/66476329/14b12b19-3447-42a8-9cc7-7a0c1ad26583)


## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-17 11:56 UTC, merged