Add Forms to Blog App 📝✨
DevKaranJ/Blog pull request #7
Opened 2024-01-18 13:12 UTC by DevKaranJ

👋 I've successfully added forms to our Blog app, completing the designated tasks. Here's a brief overview of the changes:

- Implemented a current_user method in the ApplicationController to provide access to the first user in the database.
- Created forms for the following functionalities:

- [ ] Post creation on behalf of the current_user.
- [ ] Comment creation on behalf of the current_user.
- [ ] Allowing users to add likes to posts.

I ensured that the code adheres to Ruby best practices and resolved any linter errors. The Gitflow process has been followed diligently.

Ready for your review! 🚀🔍

2024-01-18 15:12 UTC, danmainah requested changes
Hi @DevKaranJ , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Added the current_user method in the ApplicationController to make current user data available to all controllers.
✔️ Added action methods to create posts, comments, and likes
✔️ Added forms to add new posts, comments and a button to add likes to a post.

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-01-18 15:12 UTC, danmainah commented on app/controllers/posts_controller.rb
> +  end
- [ ] @DevKaranJ Great work adding a method to add a new post , however your method doesn't use the current_user method as per the project requirement and the post params is missing the title parameter, kindly consider fixing this error
![image](https://github.com/DevKaranJ/Blog/assets/61408860/b8feafa0-bb6e-422c-82c8-50dc7f07682f)

2024-01-18 15:12 UTC, danmainah commented on app/controllers/comments_controller.rb
> +  end
- [ ] @DevKaranJ Great work adding a method to add new comments,  however you have not used the `current_user` method as required in the project requirements.
![image](https://github.com/DevKaranJ/Blog/assets/61408860/69689a45-c3a7-4083-947c-ec93cc410ba3)

2024-01-18 19:04 UTC, OyePriscilla requested changes
Hi @DevKaranJ 👏 👏, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Included title as post params ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 19:04 UTC, OyePriscilla commented on app/controllers/posts_controller.rb
> +    end
- [ ] I was unable to create a new post successfully for the `current_user`, kindly work around the `current_user` implementation properly as suggested earlier. 🙏

2024-01-18 19:04 UTC, OyePriscilla commented on app/controllers/comments_controller.rb
> +
- [ ] In the process of creating a comment for a given post for the `current_user`, kindly ensure that comment is successfully created for the current_user. 🙏

2024-01-19 10:46 UTC, Ibizugbe approved these changes
Hi @DevKaranJ 👋🏼👋🏼👋🏼, 

![approved](https://github.com/DevKaranJ/Blog/assets/64643995/98818c09-c53a-451b-b01a-9484bd19f8ac)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Posts and comments are successfully being created👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 10:56 UTC, merged